
package mosqueira.pureStream;

/**
 *
 * @author Mosqueira
 */
public class AboutDialog extends javax.swing.JDialog {
    
   

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(400,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameDeveloped = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblRecursos = new javax.swing.JLabel();
        btnCloseAbout = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitleAbout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abaut Dialog");
        setBackground(new java.awt.Color(0, 153, 204));
        setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        setModal(true);
        setName("AboutDialog"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 250));
        getContentPane().setLayout(null);

        lblNameDeveloped.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblNameDeveloped.setForeground(new java.awt.Color(255, 255, 255));
        lblNameDeveloped.setText("Developed By Romina Marlene Mosqueira Rodriguez");
        getContentPane().add(lblNameDeveloped);
        lblNameDeveloped.setBounds(50, 100, 280, 20);

        lblCurso.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("Curso: Desarrollo de interfaces ");
        getContentPane().add(lblCurso);
        lblCurso.setBounds(50, 140, 200, 20);

        lblRecursos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblRecursos.setForeground(new java.awt.Color(255, 255, 255));
        lblRecursos.setText("Recursos: yt-dlp, ffmpeg, icons8, etc.");
        getContentPane().add(lblRecursos);
        lblRecursos.setBounds(50, 180, 210, 20);

        btnCloseAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnCloseAbout.setForeground(new java.awt.Color(0, 0, 153));
        btnCloseAbout.setText("Close");
        btnCloseAbout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCloseAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAboutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseAbout);
        btnCloseAbout.setBounds(140, 220, 90, 24);

        jDesktopPane1.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 380, 10);

        lblTitleAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblTitleAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleAbout.setText("Pure Stream Downloader");
        jDesktopPane1.add(lblTitleAbout);
        lblTitleAbout.setBounds(120, 30, 140, 20);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 420, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAboutActionPerformed
        dispose();
        btnCloseAbout.setVisible(false);
    }//GEN-LAST:event_btnCloseAboutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAbout;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblNameDeveloped;
    private javax.swing.JLabel lblRecursos;
    private javax.swing.JLabel lblTitleAbout;
    // End of variables declaration//GEN-END:variables
}
