package mosqueira.pureStream;

import javax.swing.JOptionPane;

/**
 *
 * @author Mosqueira
 */
public class MainFrame extends javax.swing.JFrame {

//    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private PanelPrincipal panelPrincipal;
    private PanelPreferencias panelPreferencias;

    public MainFrame() {
        initComponents();
        setResizable(false);
        this.setSize(800, 900);
        setLocationRelativeTo(null);
        mostrarPanelPrincipal();
    }

    //Paneles
    private void mostrarPanelPrincipal() {
        panelPrincipal = new PanelPrincipal();
        getContentPane().add(panelPrincipal);
        revalidate();
        repaint();
    }

    private void mostrarPanelPreferencias() {
        getContentPane().removeAll(); // Elimina todo lo anterior
        getContentPane().add(new PanelPreferencias());
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmnMenu = new javax.swing.JMenuBar();
        jmnFile = new javax.swing.JMenu();
        jmnExit = new javax.swing.JMenuItem();
        jmnEdit = new javax.swing.JMenu();
        jmnSelectPath = new javax.swing.JMenuItem();
        jmnLimit = new javax.swing.JMenuItem();
        jmnPreferences = new javax.swing.JMenuItem();
        jmnHelp = new javax.swing.JMenu();
        jmnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PureStream");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jmnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmnMenu.setForeground(new java.awt.Color(0, 102, 153));

        jmnFile.setText("File");
        jmnFile.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        jmnExit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jmnExit.setText("Exit");
        jmnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnExitActionPerformed(evt);
            }
        });
        jmnFile.add(jmnExit);

        jmnMenu.add(jmnFile);

        jmnEdit.setText("Edit");
        jmnEdit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        jmnSelectPath.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jmnSelectPath.setText("Select yt-dlp Path");
        jmnSelectPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnSelectPathActionPerformed(evt);
            }
        });
        jmnEdit.add(jmnSelectPath);

        jmnLimit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jmnLimit.setText("Limit Download");
        jmnLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnLimitActionPerformed(evt);
            }
        });
        jmnEdit.add(jmnLimit);

        jmnPreferences.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jmnPreferences.setText("Preferences");
        jmnPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnPreferencesActionPerformed(evt);
            }
        });
        jmnEdit.add(jmnPreferences);

        jmnMenu.add(jmnEdit);

        jmnHelp.setText("Help");
        jmnHelp.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        jmnAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jmnAbout.setText("About");
        jmnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnAboutActionPerformed(evt);
            }
        });
        jmnHelp.add(jmnAbout);

        jmnMenu.add(jmnHelp);

        setJMenuBar(jmnMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmnLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmnLimitActionPerformed

    private void jmnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmnExitActionPerformed

    private void jmnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnAboutActionPerformed
        AboutDialog aboutD = new AboutDialog(this, true);
        aboutD.setLocationRelativeTo(this);
        aboutD.setVisible(true);
    }//GEN-LAST:event_jmnAboutActionPerformed

    private void jmnPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnPreferencesActionPerformed
        mostrarPanelPreferencias();
    }//GEN-LAST:event_jmnPreferencesActionPerformed

    private void jmnSelectPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnSelectPathActionPerformed
        mostrarPanelPrincipal();
    }//GEN-LAST:event_jmnSelectPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //  logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jmnAbout;
    private javax.swing.JMenu jmnEdit;
    private javax.swing.JMenuItem jmnExit;
    private javax.swing.JMenu jmnFile;
    private javax.swing.JMenu jmnHelp;
    private javax.swing.JMenuItem jmnLimit;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JMenuItem jmnPreferences;
    private javax.swing.JMenuItem jmnSelectPath;
    // End of variables declaration//GEN-END:variables
}
