package mosqueira.pureStream;
import javax.swing.JOptionPane;
import mosqueira.pureStream.Dialogs.AboutDialog;
import mosqueira.pureStream.Paneles.PanelPrincipal;
import mosqueira.pureStream.Paneles.PreferencesPanel;

/**
 *
 * @author Mosqueira
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private PanelPrincipal panelPrincipal;
    private PreferencesPanel panelPreferencias;

    public MainFrame() {
        initComponents();
        setTitle("YT Donwloader");
        setResizable(false);//No se puede redimensionar
        setSize(800, 800);
        setLocationRelativeTo(null);//Centrar ventana
         setDefaultCloseOperation(EXIT_ON_CLOSE);
        panelPreferencias = new PreferencesPanel(this);
        panelPrincipal = new PanelPrincipal(panelPreferencias); // pasamos referencia de preferencias
        setContentPane(panelPrincipal);  // por defecto mostramos el panel principal
        
    }

    //Paneles
    public  void mostrarPanelPrincipal() {
        setContentPane(panelPrincipal);
        revalidate();
        repaint();
    }

    private void mostrarPanelPreferencias() {
        setContentPane(panelPreferencias);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmnMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        itemPreferences = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PureStream");
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jmnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmnMenu.setForeground(new java.awt.Color(0, 102, 153));

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        itemExit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menuFile.add(itemExit);

        jmnMenu.add(menuFile);

        menuEdit.setText("Edit");
        menuEdit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        itemPreferences.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        itemPreferences.setText("Preferences");
        itemPreferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPreferencesActionPerformed(evt);
            }
        });
        menuEdit.add(itemPreferences);

        jmnMenu.add(menuEdit);

        menuHelp.setText("Help");
        menuHelp.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        itemAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        itemAbout.setText("About");
        itemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(itemAbout);

        jmnMenu.add(menuHelp);

        setJMenuBar(jmnMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed

        if (JOptionPane.showConfirmDialog(this, "¿Seguro que quieres salir?",
                "Confirmar salida", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAboutActionPerformed
        AboutDialog aboutD = new AboutDialog(this, true);
        aboutD.setLocationRelativeTo(this);
        aboutD.setVisible(true);
    }//GEN-LAST:event_itemAboutActionPerformed

    private void itemPreferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPreferencesActionPerformed
        mostrarPanelPreferencias();

    }//GEN-LAST:event_itemPreferencesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbout;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemPreferences;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    // End of variables declaration//GEN-END:variables
}
