package mosqueira.pureStream;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingWorker;

/**
 *
 * @author Mosqueira
 */

public class PanelPrincipal extends javax.swing.JPanel {

    private String url;
    private String YTDLP_PATH=System.getenv("yt-dlp")+ "\\yt-dlp.exe";

    public PanelPrincipal() {
        initComponents();
        setSize(800, 900);
        buttonGroupFormato.add(jrbSelectionMp3);
        buttonGroupFormato.add(jrbSelectionMp4);
    }

    private void exetDOnwloadSecondPlane(String url) {
        jTxtLog.append("Trying to download"+ jtfEntrada.getText());
        jTxtLog.append(YTDLP_PATH);
        SwingWorker<Void, String> worker = new SwingWorker<Void,String>() {
            @Override
            protected Void doInBackground() throws Exception {
                ProcessBuilder pb = new ProcessBuilder("C:\\Program Files\\yt-dlp\\yt-dlp.exe");
                pb.redirectErrorStream(true);  // mezcla salida estándar y errores
                Process proceso = pb.start();

                // Captura la salida de yt-dlp
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(proceso.getInputStream(), StandardCharsets.UTF_8))) {

                    String line;
                    while ((line = reader.readLine()) != null) {
                        publish(line + "\n");
                    }
                }

                int exitCode = proceso.waitFor();
                publish("\nProceso finalizado con código: " + exitCode + "\n");
                return null;
            }

            @Override
            protected void process(List<String> chunks) {
                for (String line : chunks) {
                    jTxtLog.append(line);
                }
            }

            @Override
            protected void done() {
                jTxtLog.append("\nDescarga terminada \n");
            }
        };

        // 🔹 IMPORTANTE: ejecutar el SwingWorker
        worker.execute();
    }

    private List<String> construirComando(String url) {
        List<String> cmd = new ArrayList<>();

        // Ruta del ejecutable
        String ytDlpPath = "C:\\Program Files\\yt-dlp\\yt-dlp.exe";
        cmd.add(ytDlpPath);

        // Verificamos formato
        if (jrbSelectionMp4.isSelected()) {
            cmd.add("-f");
            cmd.add("bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4");
        } else if (jrbSelectionMp3.isSelected()) {
            cmd.add("-f");
            cmd.add("bestaudio");
            cmd.add("--extract-audio");
            cmd.add("--audio-format");
            cmd.add("mp3");
        } else {
            jTxtLog.append("Selecciona un formato (MP3 o MP4)\n");
        }

        // Añadimos URL
        cmd.add(url);

        return cmd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFormato = new javax.swing.ButtonGroup();
        lblUrl = new javax.swing.JLabel();
        jtfEntrada = new java.awt.TextField();
        btnDonwload = new javax.swing.JButton();
        jrbSelectionMp4 = new javax.swing.JRadioButton();
        jrbSelectionMp3 = new javax.swing.JRadioButton();
        jchM3U = new javax.swing.JCheckBox();
        jcbElecciones = new javax.swing.JComboBox<>();
        lblFormatoSalida = new javax.swing.JLabel();
        jslFormato = new javax.swing.JSeparator();
        jslOptionA = new javax.swing.JSeparator();
        lblAds = new javax.swing.JLabel();
        jchDelet = new javax.swing.JCheckBox();
        jchLimit = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnReproducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtLog = new javax.swing.JTextArea();

        setLayout(null);

        lblUrl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblUrl.setForeground(new java.awt.Color(0, 0, 0));
        lblUrl.setText("Url");
        add(lblUrl);
        lblUrl.setBounds(90, 40, 50, 20);

        jtfEntrada.setBackground(new java.awt.Color(204, 204, 204));
        jtfEntrada.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jtfEntrada.setText("Introduce el Link");
        jtfEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEntradaActionPerformed(evt);
            }
        });
        add(jtfEntrada);
        jtfEntrada.setBounds(150, 40, 380, 30);

        btnDonwload.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnDonwload.setForeground(new java.awt.Color(0, 0, 153));
        btnDonwload.setText("Donwload");
        btnDonwload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonwloadActionPerformed(evt);
            }
        });
        add(btnDonwload);
        btnDonwload.setBounds(550, 40, 100, 24);

        jrbSelectionMp4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jrbSelectionMp4.setForeground(new java.awt.Color(0, 0, 153));
        jrbSelectionMp4.setText("Video(Mp4)");
        jrbSelectionMp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSelectionMp4ActionPerformed(evt);
            }
        });
        add(jrbSelectionMp4);
        jrbSelectionMp4.setBounds(50, 120, 120, 25);

        jrbSelectionMp3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jrbSelectionMp3.setForeground(new java.awt.Color(0, 0, 153));
        jrbSelectionMp3.setText("Audio(Mp3)");
        jrbSelectionMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSelectionMp3ActionPerformed(evt);
            }
        });
        add(jrbSelectionMp3);
        jrbSelectionMp3.setBounds(240, 120, 110, 25);

        jchM3U.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jchM3U.setForeground(new java.awt.Color(0, 0, 153));
        jchM3U.setText("Crear archivo  .m3u");
        jchM3U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchM3UActionPerformed(evt);
            }
        });
        add(jchM3U);
        jchM3U.setBounds(10, 240, 210, 24);

        jcbElecciones.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jcbElecciones.setForeground(new java.awt.Color(0, 0, 153));
        jcbElecciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1080p", "720p", "480p", "solo audio" }));
        add(jcbElecciones);
        jcbElecciones.setBounds(450, 130, 110, 26);

        lblFormatoSalida.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblFormatoSalida.setForeground(new java.awt.Color(0, 0, 0));
        lblFormatoSalida.setText("Formato de Salida ");
        add(lblFormatoSalida);
        lblFormatoSalida.setBounds(140, 100, 160, 20);
        add(jslFormato);
        jslFormato.setBounds(0, 90, 790, 10);
        add(jslOptionA);
        jslOptionA.setBounds(10, 190, 780, 10);

        lblAds.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblAds.setForeground(new java.awt.Color(0, 0, 0));
        lblAds.setText("Opciones adicionales");
        add(lblAds);
        lblAds.setBounds(20, 200, 170, 20);

        jchDelet.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jchDelet.setForeground(new java.awt.Color(0, 0, 153));
        jchDelet.setText("Eliminar anuncios");
        add(jchDelet);
        jchDelet.setBounds(10, 280, 210, 24);

        jchLimit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jchLimit.setForeground(new java.awt.Color(0, 0, 153));
        jchLimit.setText("Limitar Velocidad de descarga");
        add(jchLimit);
        jchLimit.setBounds(10, 320, 210, 24);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resolución ");
        add(jLabel1);
        jLabel1.setBounds(460, 100, 120, 20);

        btnReproducir.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnReproducir.setForeground(new java.awt.Color(0, 0, 153));
        btnReproducir.setText("Reproducir");
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });
        add(btnReproducir);
        btnReproducir.setBounds(320, 730, 120, 27);

        jTxtLog.setBackground(new java.awt.Color(204, 204, 204));
        jTxtLog.setColumns(20);
        jTxtLog.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTxtLog.setRows(5);
        jScrollPane1.setViewportView(jTxtLog);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 390, 790, 290);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEntradaActionPerformed

    }//GEN-LAST:event_jtfEntradaActionPerformed

    private void btnDonwloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonwloadActionPerformed
        url = jtfEntrada.getText().trim();
        if (url.isEmpty()) {
            jTxtLog.append("Por favor, introduce una URL válida.\n");
            return;
        }
        exetDOnwloadSecondPlane(url);  
    }//GEN-LAST:event_btnDonwloadActionPerformed

    private void jrbSelectionMp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSelectionMp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSelectionMp4ActionPerformed

    private void jrbSelectionMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSelectionMp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSelectionMp3ActionPerformed

    private void jchM3UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchM3UActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchM3UActionPerformed

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
       
    }//GEN-LAST:event_btnReproducirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonwload;
    private javax.swing.JButton btnReproducir;
    private javax.swing.ButtonGroup buttonGroupFormato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtLog;
    private javax.swing.JComboBox<String> jcbElecciones;
    private javax.swing.JCheckBox jchDelet;
    private javax.swing.JCheckBox jchLimit;
    private javax.swing.JCheckBox jchM3U;
    private javax.swing.JRadioButton jrbSelectionMp3;
    private javax.swing.JRadioButton jrbSelectionMp4;
    private javax.swing.JSeparator jslFormato;
    private javax.swing.JSeparator jslOptionA;
    private java.awt.TextField jtfEntrada;
    private javax.swing.JLabel lblAds;
    private javax.swing.JLabel lblFormatoSalida;
    private javax.swing.JLabel lblUrl;
    // End of variables declaration//GEN-END:variables
}
