package mosqueira.pureStream.Paneles;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import mosqueira.pureStream.MainFrame;
import mosqueira.pureStream.Modelo.MediaFile;
import mosqueira.pureStream.Modelo.MediaTableModel;

/**
 * LibraryPanel displays all downloaded media files (audio/video) and allows the
 * user to search, filter, and delete them from the library.
 *
 * @author Romina
 */
public class LibraryPanel extends javax.swing.JPanel {

    private static final String BIBLIOTECA_FILE = "mediaLibrary.dat";
    private MediaTableModel tableModel;
    private DefaultListModel<MediaFile> listModel;
    private List<MediaFile> allMediaFiles;
    private MainFrame mainFrame;

    /**
     * Constructor: Initializes the panel with reference to the main frame and
     * table model.
     */
    public LibraryPanel(MainFrame mainFrame, MediaTableModel tableModel) {
        this.mainFrame = mainFrame;
        this.tableModel = tableModel;
        initComponents();
        setSize(800, 800);

        // Initialize the list model and assign it to the JList
        listModel = new DefaultListModel<>();
        jdownloadsList.setModel((javax.swing.ListModel) listModel);
        allMediaFiles = new ArrayList<>();

        loadMediaFiles();  // load from download folder
        cargarBiblioteca(); // load serialized library if exists
    }

    /**
     * Loads all media files from the downloads directory and populates the
     * table and list.
     */
    private void loadMediaFiles() {
        File downloadDir = new File(mainFrame.getRutaDescargas());
        if (!downloadDir.exists()) {
            downloadDir.mkdirs();
        }

        File[] files = downloadDir.listFiles();
        if (files != null) {
            for (File f : files) {
                MediaFile media = new MediaFile(f);
                if (!allMediaFiles.contains(media)) { 
                    allMediaFiles.add(media);
                    tableModel.addMediaFile(media);
                    listModel.addElement(media);
                }
            }
        }

        jTblDetails.setModel(tableModel);
    }

    /**
     * Save library to disk via serialization 
     */
    public void guardarBiblioteca() {
        if (allMediaFiles.isEmpty()) {
            return;
        }
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream(BIBLIOTECA_FILE))) {
            oos.writeObject(allMediaFiles);
            System.out.println("Biblioteca guardada correctamente.");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     *Load library from serialized file if it exists 
     */
    private void cargarBiblioteca() {
        File file = new File(BIBLIOTECA_FILE);
        if (file.exists()) {
            try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(file))) {
                List<MediaFile> archivos = (List<MediaFile>) ois.readObject();
                receiveFiles(archivos);
                System.out.println("Biblioteca cargada correctamente.");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
/** Add a new media file to library */
    public void addMediaFile(MediaFile media) {
        allMediaFiles.add(media);
        tableModel.addMediaFile(media);
        listModel.addElement(media);
        guardarBiblioteca(); // opcional: guardar inmediatamente
    }

    /**
     * Update view and internal list with provided files 
     */
    public void receiveFiles(List<MediaFile> archivos) {
        allMediaFiles.clear();
        allMediaFiles.addAll(archivos);
        tableModel.clearAll();
        listModel.clear();

        for (MediaFile archivo : archivos) {
            tableModel.addMediaFile(archivo);
            listModel.addElement(archivo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollList = new javax.swing.JScrollPane();
        jdownloadsList = new javax.swing.JList<>();
        jScrollTable = new javax.swing.JScrollPane();
        jTblDetails = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jSeparatorListDownload = new javax.swing.JSeparator();
        jtxtSearch = new javax.swing.JTextField();
        jcbFiltrados = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details Download", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        setLayout(null);

        jScrollList.setViewportView(jdownloadsList);

        add(jScrollList);
        jScrollList.setBounds(20, 420, 520, 290);

        jTblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollTable.setViewportView(jTblDetails);

        add(jScrollTable);
        jScrollTable.setBounds(20, 40, 520, 300);

        btnSearch.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(550, 50, 72, 27);

        btnDelete.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(550, 310, 90, 27);

        jSeparatorListDownload.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Download", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        add(jSeparatorListDownload);
        jSeparatorListDownload.setBounds(0, 380, 820, 390);

        jtxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchActionPerformed(evt);
            }
        });
        add(jtxtSearch);
        jtxtSearch.setBounds(550, 100, 220, 40);

        jcbFiltrados.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jcbFiltrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Video", "Audio" }));
        jcbFiltrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFiltradosActionPerformed(evt);
            }
        });
        add(jcbFiltrados);
        jcbFiltrados.setBounds(550, 180, 120, 26);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Executes the search and filter logic when the user types or changes
     * filters.
     */
    private void jtxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchActionPerformed
        String searchText = jtxtSearch.getText().toLowerCase().trim();
        String filter = jcbFiltrados.getSelectedItem().toString();

        List<MediaFile> filtered = allMediaFiles.stream()
                .filter(f -> f.getFileName().toLowerCase().contains(searchText))
                .filter(f -> switch (filter) {
            case "Video" ->
                f.getMimeType().contains("video");
            case "Audio" ->
                f.getMimeType().contains("audio");
            default ->
                true;
        })
                .collect(Collectors.toList());

        tableModel.clearAll();
        listModel.clear();
        filtered.forEach(f -> {
            tableModel.addMediaFile(f);
            listModel.addElement(f);
        });


    }//GEN-LAST:event_jtxtSearchActionPerformed
    /**
     * Handles combo box filter selection (Audio, Video, All).
     */
    private void jcbFiltradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFiltradosActionPerformed
        if (allMediaFiles != null && !allMediaFiles.isEmpty()) {
            jtxtSearchActionPerformed(null);
        }

    }//GEN-LAST:event_jcbFiltradosActionPerformed
    /**
     * Handles the deletion of a selected file from the table and disk.
     */
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = jTblDetails.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a file to delete.");
            return;
        }

        MediaFile fileToDelete = tableModel.getMediaFileAt(selectedRow);
        File file = new File(fileToDelete.getFilePath());

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this file?\n" + file.getName(),
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (file.delete()) {
                tableModel.removeMediaFile(selectedRow);
                listModel.removeElement(fileToDelete);
                allMediaFiles.remove(fileToDelete);
                JOptionPane.showMessageDialog(this, "File deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the file.");
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed
    /**
     * Triggers the search manually when pressing the Search button.
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        jtxtSearchActionPerformed(evt);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollList;
    private javax.swing.JScrollPane jScrollTable;
    private javax.swing.JSeparator jSeparatorListDownload;
    private javax.swing.JTable jTblDetails;
    private javax.swing.JComboBox<String> jcbFiltrados;
    private javax.swing.JList<String> jdownloadsList;
    private javax.swing.JTextField jtxtSearch;
    // End of variables declaration//GEN-END:variables
}
