package mosqueira.pureStream.Paneles;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mosqueira.pureStream.ControladorInterno.DownloadTask;
import mosqueira.pureStream.MainFrame;
import mosqueira.pureStream.Modelo.MediaFile;
import mosqueira.pureStream.Modelo.MediaTableModel;

/**
 * Main panel that handles URL input, download actions, and interaction with
 * Preferences and Library panels.
 *
 * @author Romina
 */
public class PanelPrincipal extends javax.swing.JPanel {

    // Reference to the preferences panel where the user sets the download folder
    private PreferencesPanel preferencesPanel;

    // Stores the path of the last downloaded file
    private String lastDownloadedFile;

    // Reference to the main frame to switch between panels
    private MainFrame mainFrame;


    /**
     * Constructs the main download panel. Initializes references to the
     * PreferencesPanel, MainFrame, and shared MediaTableModel.
     *
     * @param panelPref Reference to the preferences configuration panel
     * @param mainFrame Reference to the main window for switching panels
     * @param tableModel Shared model containing downloaded media
     */
    public PanelPrincipal(PreferencesPanel panelPref, MainFrame mainFrame, MediaTableModel tableModel) {
        initComponents();

        this.preferencesPanel = panelPref;
        this.mainFrame = mainFrame;
        // Show current download path in the text field
        jtxtFolderDownload.setText(mainFrame.getRutaDescargas());
    }

    public MainFrame getMainFrame() {
        return mainFrame;
    }

    /**
     * Sets a reference to the PreferencesPanel instance.
     *
     * @param panelPreferencias new PreferencesPanel reference
     */
    public void setPanelPreferencias(PreferencesPanel panelPreferencias) {
        this.preferencesPanel = panelPreferencias;
    }
    /**
     * Called when a file is successfully downloaded.
     * Updates log and stores last downloaded file path.
     */
    public void notifyDownloaded(MediaFile mf) {
        lastDownloadedFile = mf.getFile().getAbsolutePath();
        jTxtLog.append("Downloaded: " + lastDownloadedFile + "\n");
        mainFrame.notifyDownloadedMedia(mf);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUrl = new javax.swing.JLabel();
        btnDownload = new javax.swing.JButton();
        lblCalidad = new javax.swing.JLabel();
        jslFormato = new javax.swing.JSeparator();
        jslOptionA = new javax.swing.JSeparator();
        btnReproducir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtLog = new javax.swing.JTextArea();
        btnOpenLibrary = new javax.swing.JButton();
        comboFormat = new javax.swing.JComboBox<>();
        comboQuality = new javax.swing.JComboBox<>();
        lblFormatoSalida1 = new javax.swing.JLabel();
        jtxtInsertUrl = new javax.swing.JTextField();
        btnSearchFolderDownload = new javax.swing.JButton();
        jtxtFolderDownload = new javax.swing.JTextField();
        lblSelectFolderDownload = new javax.swing.JLabel();

        setLayout(null);

        lblUrl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblUrl.setForeground(new java.awt.Color(0, 0, 0));
        lblUrl.setText("Url");
        add(lblUrl);
        lblUrl.setBounds(120, 50, 40, 20);

        btnDownload.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(0, 0, 153));
        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        add(btnDownload);
        btnDownload.setBounds(570, 50, 100, 24);

        lblCalidad.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblCalidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCalidad.setText("Quality");
        add(lblCalidad);
        lblCalidad.setBounds(490, 250, 90, 20);
        add(jslFormato);
        jslFormato.setBounds(0, 130, 790, 10);
        add(jslOptionA);
        jslOptionA.setBounds(10, 320, 780, 10);

        btnReproducir.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnReproducir.setForeground(new java.awt.Color(0, 0, 153));
        btnReproducir.setText("Reproducir");
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });
        add(btnReproducir);
        btnReproducir.setBounds(130, 670, 120, 27);

        jTxtLog.setBackground(new java.awt.Color(204, 204, 204));
        jTxtLog.setColumns(20);
        jTxtLog.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTxtLog.setRows(5);
        jScrollPane1.setViewportView(jTxtLog);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 350, 790, 290);

        btnOpenLibrary.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnOpenLibrary.setForeground(new java.awt.Color(0, 0, 153));
        btnOpenLibrary.setText("Details");
        btnOpenLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLibraryActionPerformed(evt);
            }
        });
        add(btnOpenLibrary);
        btnOpenLibrary.setBounds(500, 670, 120, 30);

        comboFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mp4", "mp3" }));
        comboFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFormatActionPerformed(evt);
            }
        });
        add(comboFormat);
        comboFormat.setBounds(190, 290, 72, 22);

        comboQuality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1080p", "720p", "480p", "360p" }));
        comboQuality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboQualityActionPerformed(evt);
            }
        });
        add(comboQuality);
        comboQuality.setBounds(490, 290, 72, 22);

        lblFormatoSalida1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblFormatoSalida1.setForeground(new java.awt.Color(0, 0, 0));
        lblFormatoSalida1.setText("Output Format");
        add(lblFormatoSalida1);
        lblFormatoSalida1.setBounds(170, 250, 160, 20);

        jtxtInsertUrl.setBackground(new java.awt.Color(204, 204, 204));
        add(jtxtInsertUrl);
        jtxtInsertUrl.setBounds(170, 50, 370, 30);

        btnSearchFolderDownload.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnSearchFolderDownload.setForeground(new java.awt.Color(0, 0, 153));
        btnSearchFolderDownload.setText("Search");
        btnSearchFolderDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFolderDownloadActionPerformed(evt);
            }
        });
        add(btnSearchFolderDownload);
        btnSearchFolderDownload.setBounds(580, 180, 95, 30);

        jtxtFolderDownload.setBackground(new java.awt.Color(204, 204, 204));
        jtxtFolderDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFolderDownloadActionPerformed(evt);
            }
        });
        add(jtxtFolderDownload);
        jtxtFolderDownload.setBounds(170, 180, 370, 30);

        lblSelectFolderDownload.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblSelectFolderDownload.setForeground(new java.awt.Color(0, 0, 0));
        lblSelectFolderDownload.setText("Select download folder");
        add(lblSelectFolderDownload);
        lblSelectFolderDownload.setBounds(10, 180, 150, 30);
    }// </editor-fold>//GEN-END:initComponents
     /**
     * Starts a new download using DownloadTask.
     */
    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        if (mainFrame.getRutaDescargas() == null) {
            JOptionPane.showMessageDialog(this,
                    "Select a download folder first.", "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String url = jtxtInsertUrl.getText().trim();
        if (url.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insert a URL.");
            return;
        }

        jTxtLog.setText("");
        jTxtLog.append("Downloading: " + url + "\n");
  // Create and execute background download task
        DownloadTask task = new DownloadTask(
                url,
                preferencesPanel,
                jTxtLog,
                comboFormat,
                comboQuality,
                this
        );
        task.execute();


    }//GEN-LAST:event_btnDownloadActionPerformed
    /**
     * Opens the last downloaded file using the default system application.
     */
    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
        if (lastDownloadedFile == null) {
            jTxtLog.append("Primero descarga un archivo para poder reproducirlo.\n");
            return;
        }

        try {
            
            java.nio.file.Path path = java.nio.file.Paths.get(lastDownloadedFile);
            File file = path.toFile();

            if (!file.exists()) {
                jTxtLog.append("No se encontró el archivo descargado: " + lastDownloadedFile + "\n");
                return;
            }

            jTxtLog.append("Reproduciendo: " + file.getAbsolutePath() + "\n");

            java.awt.Desktop.getDesktop().open(file);

        } catch (Exception e) {
            jTxtLog.append("ERROR al reproducir el archivo: " + e.getMessage() + "\n");
        }
    }//GEN-LAST:event_btnReproducirActionPerformed
    /**
     * Opens the Library panel to show all downloaded media files.
     */
    private void btnOpenLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLibraryActionPerformed
        mainFrame.showLibraryPanel();
    }//GEN-LAST:event_btnOpenLibraryActionPerformed

    private void comboQualityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboQualityActionPerformed

    }//GEN-LAST:event_comboQualityActionPerformed

    private void comboFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFormatActionPerformed
    /**
     * Lets the user choose a folder for saving downloads.
     */
    private void btnSearchFolderDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFolderDownloadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String ruta = chooser.getSelectedFile().getAbsolutePath();
            jtxtFolderDownload.setText(ruta);
            mainFrame.setRutaDescargas(ruta);
        }
    }//GEN-LAST:event_btnSearchFolderDownloadActionPerformed

    private void jtxtFolderDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFolderDownloadActionPerformed

    }//GEN-LAST:event_jtxtFolderDownloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnOpenLibrary;
    private javax.swing.JButton btnReproducir;
    private javax.swing.JButton btnSearchFolderDownload;
    private javax.swing.JComboBox<String> comboFormat;
    private javax.swing.JComboBox<String> comboQuality;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtLog;
    private javax.swing.JSeparator jslFormato;
    private javax.swing.JSeparator jslOptionA;
    private javax.swing.JTextField jtxtFolderDownload;
    private javax.swing.JTextField jtxtInsertUrl;
    private javax.swing.JLabel lblCalidad;
    private javax.swing.JLabel lblFormatoSalida1;
    private javax.swing.JLabel lblSelectFolderDownload;
    private javax.swing.JLabel lblUrl;
    // End of variables declaration//GEN-END:variables
}
