package mosqueira.pureStream.Paneles;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mosqueira.pureStream.MainFrame;

/**
 *
 * PreferencesPanel allows the user to configure additional settings for the
 * application, such as creating an M3U file, limiting download speed, and
 * selecting the download path. This panel communicates with the MainFrame to
 * update and store configuration values.
 *
 * @author Romina
 */
public class PreferencesPanel extends javax.swing.JPanel {

    // Reference to the MainFrame to update global configuration
    private MainFrame mainFrame;

    /**
     * Constructs the PreferencesPanel and initializes its components.
     *
     * @param mainFrame Reference to the MainFrame for navigation and data
     * sharing.
     */
    public PreferencesPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        cargarPreferencias();

    }

    /**
     * Loads saved settings from MainFrame into UI controls.
     */

    public void cargarPreferencias() {

        jchM3U.setSelected(mainFrame.isCrearM3U());
        // Checkbox Limitar velocidad
        jchLimit.setSelected(mainFrame.isLimitarVelocidad());
        jSliderLimit.setEnabled(mainFrame.isLimitarVelocidad());
        jSliderLimit.setValue(mainFrame.getLimiteVelocidad());
        jtxtExecutable.setText(mainFrame.getExecutablePath());
    }

    /**
     * Returns the selected download directory path.
     */
    public boolean isCrearM3U() {
        return jchM3U.isSelected();
    }

    /**
     * Returns the selected yt-dlp executable path.
     */
    public String getExecutablePath() {
        return jtxtExecutable.getText().trim();
    }

    /**
     * Returns whether the user has enabled download speed limiting.
     */
    public boolean isLimitarVelocidad() {
        return jchLimit.isSelected();
    }

    /**
     * Returns the numeric value of the download speed limit (in KB/s).
     */
    public int getLimiteVelocidad() {
        return jSliderLimit.getValue(); // en KB/s
    }

    /**
     * Returns the reference to the MainFrame instance.
     */
    public MainFrame getMainFrame() {
        return mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jchM3U = new javax.swing.JCheckBox();
        lblAds = new javax.swing.JLabel();
        jchLimit = new javax.swing.JCheckBox();
        lblSelectPath = new javax.swing.JLabel();
        btnSaveAndReturn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jtxtExecutable = new javax.swing.JTextField();
        jSearchPath = new javax.swing.JButton();
        jSliderLimit = new javax.swing.JSlider();
        jlblValue = new javax.swing.JLabel();

        setLayout(null);

        jchM3U.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jchM3U.setForeground(new java.awt.Color(0, 0, 0));
        jchM3U.setText("Crear archivo  .m3u");
        jchM3U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchM3UActionPerformed(evt);
            }
        });
        add(jchM3U);
        jchM3U.setBounds(100, 190, 150, 40);

        lblAds.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        lblAds.setForeground(new java.awt.Color(0, 0, 0));
        lblAds.setText("Opciones adicionales");
        add(lblAds);
        lblAds.setBounds(230, 30, 240, 30);

        jchLimit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jchLimit.setForeground(new java.awt.Color(0, 0, 0));
        jchLimit.setText("Limitar Velocidad de descarga");
        jchLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchLimitActionPerformed(evt);
            }
        });
        add(jchLimit);
        jchLimit.setBounds(370, 190, 230, 40);

        lblSelectPath.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblSelectPath.setForeground(new java.awt.Color(0, 0, 0));
        lblSelectPath.setText("Select yt-dlp executable");
        add(lblSelectPath);
        lblSelectPath.setBounds(20, 100, 160, 30);

        btnSaveAndReturn.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnSaveAndReturn.setForeground(new java.awt.Color(0, 0, 153));
        btnSaveAndReturn.setText("Save and Return");
        btnSaveAndReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAndReturnActionPerformed(evt);
            }
        });
        add(btnSaveAndReturn);
        btnSaveAndReturn.setBounds(250, 400, 160, 30);
        add(jSeparator1);
        jSeparator1.setBounds(10, 160, 660, 10);

        jtxtExecutable.setBackground(new java.awt.Color(204, 204, 204));
        jtxtExecutable.setText("C:\\Program Files\\yt-dlp\\yt-dlp.exe");
        jtxtExecutable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtExecutableActionPerformed(evt);
            }
        });
        add(jtxtExecutable);
        jtxtExecutable.setBounds(190, 100, 340, 30);

        jSearchPath.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jSearchPath.setForeground(new java.awt.Color(0, 0, 153));
        jSearchPath.setText("Search");
        jSearchPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchPathActionPerformed(evt);
            }
        });
        add(jSearchPath);
        jSearchPath.setBounds(540, 100, 100, 30);

        jSliderLimit.setMajorTickSpacing(500);
        jSliderLimit.setMaximum(5000);
        jSliderLimit.setMinimum(50);
        jSliderLimit.setMinorTickSpacing(50);
        jSliderLimit.setPaintTicks(true);
        jSliderLimit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderLimitStateChanged(evt);
            }
        });
        add(jSliderLimit);
        jSliderLimit.setBounds(350, 260, 280, 40);

        jlblValue.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jlblValue.setForeground(new java.awt.Color(0, 0, 153));
        add(jlblValue);
        jlblValue.setBounds(440, 230, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Updates MainFrame when the user toggles the "Create .m3u" checkbox.
     */
    private void jchM3UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchM3UActionPerformed
        mainFrame.setCrearM3U(jchM3U.isSelected());
    }//GEN-LAST:event_jchM3UActionPerformed

    /**
     * Enables or disables the speed limit slider when toggled.
     */
    private void jchLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchLimitActionPerformed
        mainFrame.setLimitarVelocidad(jchLimit.isSelected());
        jSliderLimit.setEnabled(jchLimit.isSelected());
    }//GEN-LAST:event_jchLimitActionPerformed

    /**
     * Validates preferences and returns to the main panel.
     */
    private void btnSaveAndReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAndReturnActionPerformed
        if (jtxtExecutable.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select yt-dlp executable.");
            return;
        }
        mainFrame.setExecutablePath(jtxtExecutable.getText().trim());
        mainFrame.mostrarPanelPrincipal();
    }//GEN-LAST:event_btnSaveAndReturnActionPerformed

    /**
     * Opens a file chooser to select the yt-dlp executable path.
     */
    private void jSearchPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchPathActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String ruta = chooser.getSelectedFile().getAbsolutePath();
            jtxtExecutable.setText(ruta);
            mainFrame.setExecutablePath(ruta);
        }
    }//GEN-LAST:event_jSearchPathActionPerformed

    /**
     * Updates the download speed limit value in MainFrame.
     */
    private void jSliderLimitStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderLimitStateChanged
        jlblValue.setText(jSliderLimit.getValue() + " KB/s");
    }//GEN-LAST:event_jSliderLimitStateChanged

    private void jtxtExecutableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtExecutableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtExecutableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveAndReturn;
    private javax.swing.JButton jSearchPath;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderLimit;
    private javax.swing.JCheckBox jchLimit;
    private javax.swing.JCheckBox jchM3U;
    private javax.swing.JLabel jlblValue;
    private javax.swing.JTextField jtxtExecutable;
    private javax.swing.JLabel lblAds;
    private javax.swing.JLabel lblSelectPath;
    // End of variables declaration//GEN-END:variables
}
