package mosqueira.pureStream.Dialogs;

/**
 * This class represents the "About" dialog of the Pure Stream Downloader application.
 * It provides basic information about the developer, course, and resources used.
 * 
 * The dialog is modal and can be opened from the main interface.
 * It includes labels for author information, project title, and resources used,
 * as well as a close button to dismiss the dialog.
 * 
 * @author
 * Romina Marlene Mosqueira Rodríguez
 */
public class AboutDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AboutDialog.class.getName());

    /**
     * Constructor for the AboutDialog.
     * Initializes the dialog, sets its title, size, and layout.
     *
     * @param parent The parent frame that owns this dialog.
     * @param modal  Specifies whether the dialog blocks user input to other windows.
     */
    
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Acerca de");
        setSize(400, 400);
        this.jDesktopAboutDialog.setSize(400, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopAboutDialog = new javax.swing.JDesktopPane();
        jSeparatorTitle = new javax.swing.JSeparator();
        btnCloseAbout = new javax.swing.JButton();
        lblTitleAbout = new javax.swing.JLabel();
        lblRecursos = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblNameDeveloped = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jDesktopAboutDialog.add(jSeparatorTitle);
        jSeparatorTitle.setBounds(6, 57, 388, 10);

        btnCloseAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnCloseAbout.setText("Close");
        btnCloseAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAboutActionPerformed(evt);
            }
        });
        jDesktopAboutDialog.add(btnCloseAbout);
        btnCloseAbout.setBounds(160, 260, 75, 27);

        lblTitleAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTitleAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleAbout.setText("Pure Stream Downloader");
        jDesktopAboutDialog.add(lblTitleAbout);
        lblTitleAbout.setBounds(70, 20, 230, 25);

        lblRecursos.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblRecursos.setForeground(new java.awt.Color(255, 255, 255));
        lblRecursos.setText("Recursos:  yt-dlp, ffmpeg, videos del profesor y chatgpt etc.");
        jDesktopAboutDialog.add(lblRecursos);
        lblRecursos.setBounds(10, 200, 380, 20);

        lblCurso.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblCurso.setText("Curso: Desarrollo de interfaces");
        jDesktopAboutDialog.add(lblCurso);
        lblCurso.setBounds(10, 150, 240, 20);

        lblNameDeveloped.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lblNameDeveloped.setForeground(new java.awt.Color(255, 255, 255));
        lblNameDeveloped.setText("Developed By Romina Marlene Mosqueira Rodriguez");
        jDesktopAboutDialog.add(lblNameDeveloped);
        lblNameDeveloped.setBounds(10, 100, 360, 20);

        getContentPane().add(jDesktopAboutDialog);
        jDesktopAboutDialog.setBounds(0, 0, 420, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Event handler for the "Close" button.
     * Closes the dialog when the button is clicked.
     *
     * @param evt The ActionEvent triggered by the button.
     */
    private void btnCloseAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAboutActionPerformed
        dispose(); 
        
    }//GEN-LAST:event_btnCloseAboutActionPerformed

     /**
     * Main method to test the dialog independently.
     * Launches the AboutDialog as a standalone window.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAbout;
    private javax.swing.JDesktopPane jDesktopAboutDialog;
    private javax.swing.JSeparator jSeparatorTitle;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblNameDeveloped;
    private javax.swing.JLabel lblRecursos;
    private javax.swing.JLabel lblTitleAbout;
    // End of variables declaration//GEN-END:variables
}
