package mosqueira.pureStream.Dialogs;

import java.awt.BorderLayout;
import java.awt.Color;
import mosqueira.pureStream.DesignApp.PanelUtils;

/**
 * This class represents the "About" dialog of the Pure Stream Downloader
 * application. It provides basic information about the developer, course, and
 * resources used.
 *
 * The dialog is modal and can be opened from the main interface. It includes
 * labels for author information, project title, and resources used, as well as
 * a close button to dismiss the dialog.
 *
 * @author Romina Marlene Mosqueira Rodríguez
 */
public class AboutDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(AboutDialog.class.getName());

    /**
     * Constructor for the AboutDialog. Initializes the dialog, sets its title,
     * size, and layout.
     *
     * @param parent The parent frame that owns this dialog.
     * @param modal Specifies whether the dialog blocks user input to other
     * windows.
     */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTitle("Acerca de");
        setSize(450, 350);
        setLocationRelativeTo(parent);

        jPanelRepaint.setOpaque(false);
        jScrollPane.setOpaque(false);
        jScrollPane.getViewport().setOpaque(false);

        jtextAbout1.setOpaque(true);
        jtextAbout1.setBackground(new Color(204, 204, 204));

        PanelUtils bg = new PanelUtils();
        bg.setLayout(new BorderLayout());
        bg.add(jPanelRepaint, BorderLayout.CENTER);
        setContentPane(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRepaint = new javax.swing.JPanel();
        jSeparatorTitle = new javax.swing.JSeparator();
        btnCloseAbout = new javax.swing.JButton();
        lblTitleAbout = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jtextAbout1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setModal(true);
        getContentPane().setLayout(null);

        jPanelRepaint.setLayout(null);
        jPanelRepaint.add(jSeparatorTitle);
        jSeparatorTitle.setBounds(-2, 60, 450, 10);

        btnCloseAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnCloseAbout.setText("Close");
        btnCloseAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAboutActionPerformed(evt);
            }
        });
        jPanelRepaint.add(btnCloseAbout);
        btnCloseAbout.setBounds(180, 260, 75, 27);

        lblTitleAbout.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lblTitleAbout.setForeground(new java.awt.Color(0, 0, 0));
        lblTitleAbout.setText("Pure Stream Downloader");
        jPanelRepaint.add(lblTitleAbout);
        lblTitleAbout.setBounds(100, 20, 230, 25);

        jtextAbout1.setBackground(new java.awt.Color(204, 204, 204));
        jtextAbout1.setColumns(20);
        jtextAbout1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtextAbout1.setForeground(new java.awt.Color(0, 0, 0));
        jtextAbout1.setRows(5);
        jtextAbout1.setText("Developed By Romina Marlene Mosqueira Rodriguez\n\nCurso: Desarrollo de interfaces\n\nRecursos:  yt-dlp, ffmpeg, videos del profesor y chatgpt etc.");
        jScrollPane.setViewportView(jtextAbout1);

        jPanelRepaint.add(jScrollPane);
        jScrollPane.setBounds(0, 70, 450, 180);

        getContentPane().add(jPanelRepaint);
        jPanelRepaint.setBounds(0, 10, 440, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAboutActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseAboutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseAbout;
    private javax.swing.JPanel jPanelRepaint;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSeparator jSeparatorTitle;
    private javax.swing.JTextArea jtextAbout1;
    private javax.swing.JLabel lblTitleAbout;
    // End of variables declaration//GEN-END:variables
}
